title: Andre du Toit
theme: minima
author: Jenca
email: andre@annakotze.com
description: > # this means to ignore newlines until "baseurl:"
  Here we will have open discussions regarding wealth management.
  Topics such as insurance, investements and diversification will be on the agenda every day.


# social links
twitter_username: AndreDuToit
github_username:  Jenca-git # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
